
version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: mysql_boot
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'bitly_db'
      MYSQL_ROOT_PASSWORD: 'root'
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
